name: Test AWS Connection

on:
  workflow_dispatch:

jobs:
  test-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AKIARCCRJLABNK5AE7SR }}
          aws-secret-access-key: ${{ secrets.qAnOAzlpBQ1Yoioc0S9seUhW3OZZM9gi//nGYGIy }}
          aws-region: ${{ secrets.eu-west-3 }}

      - name: Test AWS credentials validity
        run: |
          echo "Testing AWS credentials..."
          aws sts get-caller-identity

      - name: List S3 buckets
        run: |
          echo "Listing S3 buckets..."
          aws s3 ls
