name: Test AWS Connection
on:
  workflow_dispatch
jobs:
  test-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AKIARCCRJLABKB6KWX3B }}
          aws-secret-access-key: ${{ secrets.9WBnt8/k5scK+JpRS4x5jsSDJqrWzu9Wy4wH0sbA }}
          aws-region: ${{ secrets.eu-west-3 }}
      - name: Test AWS credentials validity
        run: |
          echo "Testing AWS credentials..."
          aws sts get-caller-identity
      - name: List S3 buckets
        run: |
          echo "Listing S3 buckets..."
          aws s3 ls
